### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by AnilYd14** [mike14u/shimmer-recyclerview-x#2]
This adapter is not working with the pagination as again start from top.

**Comment by M-Elnemr** [comment]
yes i have the same problem , did you solve it?

**Comment by AnilYd14** [comment]
Hello,

Yes I resolved this issue, check the internal implementation when you
notify adapter it again call setAdapter inplace to notify, that is why it's
starting from top again.
So you just need to check before calling notify on recyclerview.

**Comment by M-Elnemr** [comment]
i only call adapter.submitList(data); every time load new data

**Comment by AnilYd14** [comment]
Hello,

Are you calling hideShimmerAdapter() everytime on response,
This need to be call only once for Page=1
So you can have check if shimmer is visible then only hide.
Check the internal implementation of of hideShimmerAdapter you will get the
reason.

**Comment by M-Elnemr** [comment]
thank you so much , now it works perfectly
