### ISSUE TITLE
Shimmer horizontal

### ISSUE THREAD

**Issue by MostafaGad1911** [mike14u/shimmer-recyclerview-x#4]
Shimmer effect not showing when recycler orientation is horizontal

**Comment by mikekpl** [comment]
@MostafaGad1911 sorry for the late reply, just set your DemoLayoutManager like so:

```
shimmerRecyclerView.setDemoLayoutManager(ShimmerRecyclerViewX.LayoutMangerType.LINEAR_HORIZONTAL);
```

or in XML you can set it:

```
app:shimmer_demo_layout_manager_type="linear_horizontal"
```

Let me know if that works.
